# Generated by Django 4.2.4 on 2023-08-21 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deposit',
            old_name='cpf',
            new_name='pix',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='account',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='deposit',
            name='bank',
        ),
    ]
