# Generated by Django 4.2.4 on 2023-08-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_cpf_deposit_pix_remove_deposit_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='pix',
            field=models.CharField(max_length=100),
        ),
    ]
