# Generated by Django 4.2.4 on 2023-08-21 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_deposit_pix'),
    ]

    operations = [
        migrations.AddField(
            model_name='deposit',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
